routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Auth::routes();

Route::group(['domain' => \Config::get('app.base_url')], function () {

    Auth::routes();

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/health', function () {
        response()->json(['success' => 'success'], 200);
    });
    Route::get('/users', function () {
        // $users = \DB::connection('maindb')->table('users')->get();
        $users = \App\User::find(14);
        return $users;
    });

    Route::get('home', 'MainDomain\HomeController@index')->name('home.maindomain');
    Route::post('dashboard', ['as' => 'dashboard', 'uses' => 'MainDomain\HomeController@dashboard']);

    Route::post('/subdomain/check', 'Home\SubdomainCheckController@check')->name('subdomain.check');
    Route::post('/mobile/check', 'Home\SubdomainCheckController@check')->name('mobile.check');
    // Route::post('/sendotp', 'Home\SubdomainCheckController@sendOtp')->name('send.otp');
    Route::post('/verifyotp', 'Home\SubdomainCheckController@verifyOtp')->name('verify.otp');
    Route::get('/sendotp', 'MainDomain\HomeController@sendOtp')->name('send.otp');
    Route::post('/sendotp', 'MainDomain\HomeController@verifyOtp')->name('send.otp');
    Route::post('/verify', 'Home\VerifyController@verifyMobile')->name('verify');

    Route::get('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@index']);
    Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::get('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@index1']);
    Route::post('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@storeinfo1']);

    Route::get('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@index2']);
    Route::post('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@storeinfo2']);

    Route::get('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@index3']);
    Route::post('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@storeinfo3']);

    Route::get('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@companylogo']);
    Route::post('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@storecompanylogo']);

    Route::get('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@profilelogo']);
    Route::post('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@storeprofilelogo']);

    Route::get('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@passwordreset']);
    Route::post('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@storepassword']);

// Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::resource('skills', 'MainDomain\SkillController');
    Route::resource('achievements', 'MainDomain\AchievementController');
    Route::resource('product', 'MainDomain\ProductController');
    Route::resource('payment', 'MainDomain\PaymentController');
    Route::resource('social', 'MainDomain\SocialController');
    Route::resource('experience', 'MainDomain\ExperienceController');
    Route::resource('education', 'MainDomain\EducationController');
    Route::resource('testimonial', 'MainDomain\TestimonialController');
    Route::resource('subscription', 'MainDomain\SubscriptionController');
    Route::resource('referral', 'MainDomain\ReferralController');
    Route::resource('plan', 'MainDomain\PlanController');
    Route::resource('colorschema', 'MainDomain\ColorController');
    Route::resource('images', 'MainDomain\ImageGalleryController');
    Route::resource('location', 'MainDomain\LocationController');

    Route::get('plansub', ['as' => 'plansub', 'uses' => 'MainDomain\PlanController@CustomSubscribe']);

    Route::resource('preview', 'MainDomain\PreviewController');

    Route::get('clear_cache', function () {
        \Artisan::call('optimize:clear');
        return "Optimize is cleared";
    });

    Route::get('paypayment', ['as' => 'pay_payment', 'uses' => 'MainDomain\PayumoneyController@payment']);

    Route::get('paypayment/status', ['as' => 'pay_payment.status', 'uses' => 'MainDomain\PayumoneyController@status']);

    // Get Route For Show Payment Form
    Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay');
    Route::post('paysuccess', 'RazorpayController@paysuccess');
    Route::post('makesubscription', ['as' => 'makesubscription', 'uses' => 'RazorpayController@makeSubscription']);
    Route::post('razor-thank-you', 'RazorpayController@thankYou');

    // route for to show payment form using get method
    Route::get('pay', 'RazorpayController@pay')->name('pay');

    Route::get('getpaln/{planid}', 'RazorpayController@getPlanbyid')->name('getplan');

    // route for make payment request using post method
    Route::post('dopayment', 'RazorpayController@dopayment')->name('dopayment');
    Route::post('razorpayment', 'RazorpayController@razorPaySuccess')->name('razorpayment');

});

Route::group(['domain' => '{account}.' . \Config::get('app.base_url')], function () {

    /*
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/account', function ($account) {
    return $account;
    });
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Subdomain\DashboardController@index']);
     */
    Route::get('/', ['as' => 'vcard', 'uses' => 'Subdomain\DashboardController@index', 'middleware' => 'sub_domain_shift']);
    Route::get('/savecard', ['as' => 'makecard', 'uses' => 'Subdomain\DashboardController@CreateVcard', 'middleware' => 'sub_domain_shift']);
    Route::get('/qrcode', ['as' => 'qrcode', 'uses' => 'Subdomain\DashboardController@CreateQrcode', 'middleware' => 'sub_domain_shift']);
});

// Route::get('crop-image', 'ImageCropController@index');
// Route::post('crop-image', ['as' => 'croppie.upload-image', 'uses' => 'ImageCropController@imageCrop']);

// Route::get('image_crop', 'ImageCropController@index1');
// Route::post('image_crop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('imagecrop', 'ImageCropController@index2');
// Route::post('imagecrop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@createStep1']);
// Route::post('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@postCreateStep1']);

// Route::get('step2', 'PersonalInfoController@createStep2');
// Route::post('step2', 'PersonalInfoController@postCreateStep2');
// Route::post('remove-image', 'PersonalInfoController@removeImage');

// Route::get('step3', 'PersonalInfoController@createStep3');
// Route::post('store', 'PersonalInfoController@store');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

resources/views/gallery/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('skills.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('skills.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="sname" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Detail:</strong>
                <textarea class="form-control" style="height:150px" name="svalue" placeholder="Detail"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/gallery/edit.blade.php
@extends('layouts.app')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Color</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('colorschema.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('colorschema.update',$skill->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="sname" value="{{ $skill->sname }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <input type="color" name="svalue" id="colorpicker" value="{{ $skill->svalue }}" class="form-control colorpicker" placeholder="Color">

                </div>
            </div>
           
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>

    <script type="text/javascript">

        // $('.colorpicker').colorpicker();
        $('#color').colorpicker({});

      </script>


@endsection

resources/views/gallery/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Image Gallery Example</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- References: https://github.com/fancyapps/fancyBox -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>


    <style type="text/css">
    .gallery
    {
        display: inline-block;
        margin-top: 20px;
    }
    .close-icon{
    	border-radius: 50%;
        position: absolute;
        right: 5px;
        top: -10px;
        padding: 5px 8px;
    }
    .form-image-upload{
        background: #e8e8e8 none repeat scroll 0 0;
        padding: 15px;
    }
    </style>
</head>
<body>


<div class="container">


    <h3>Laravel - Image Gallery CRUD Example</h3>
    <form action="{{ route('images.store') }}" class="form-image-upload" method="POST" enctype="multipart/form-data">


        {!! csrf_field() !!}


        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
        </div>
        @endif


        <div class="row">
            <div class="col-md-5">
                <strong>Title:</strong>
                <input type="text" name="title" class="form-control" placeholder="Title">
            </div>
            <div class="col-md-5">
                <strong>Image:</strong>
                <input type="file" name="image" class="form-control">
            </div>
            <div class="col-md-2">
                <br/>
                <button type="submit" class="btn btn-success">Upload</button>
            </div>
        </div>


    </form> 


    <div class="row">
    <div class='list-group gallery'>


            @if($images->count())
                @foreach($images as $image)
                <div class='col-sm-4 col-xs-6 col-md-3 col-lg-3'>
                    <a class="thumbnail fancybox" rel="ligthbox" href="/storage/userdata/{{ $image->svalue }}">
                        <img class="img-responsive" alt="" src="/storage/userdata/{{ $image->svalue }}" />
                        <div class='text-center'>
                            <small class='text-muted'>{{ $image->sname }}</small>
                        </div> <!-- text-center / end -->
                    </a>
                    <form action="{{ route('images.destroy',$image->id) }}" method="POST">
                    <input type="hidden" name="_method" value="delete">
                    {!! csrf_field() !!}
                    <button type="submit" class="close-icon btn btn-danger"><i class="glyphicon glyphicon-remove"></i></button>
                    </form>
                </div> <!-- col-6 / end -->
                @endforeach
            @endif


        </div> <!-- list-group / end -->
    </div> <!-- row / end -->
</div> <!-- container / end -->


</body>


<script type="text/javascript">
    $(document).ready(function(){
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
</script>
</html>

resources/views/gallery/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('skills.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $skill->sname }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $skill->svalue }}
            </div>
        </div>
    </div>
@endsection