routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Auth::routes();

Route::group(['domain' => \Config::get('app.base_url')], function () {

    Auth::routes();

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/health', function () {
        response()->json(['success' => 'success'], 200);
    });
    Route::get('/users', function () {
        // $users = \DB::connection('maindb')->table('users')->get();
        $users = \App\User::find(14);
        return $users;
    });

    Route::get('home', 'MainDomain\HomeController@index')->name('home.maindomain');
    Route::post('dashboard', ['as' => 'dashboard', 'uses' => 'MainDomain\HomeController@dashboard']);

    Route::post('/subdomain/check', 'Home\SubdomainCheckController@check')->name('subdomain.check');
    Route::post('/mobile/check', 'Home\SubdomainCheckController@check')->name('mobile.check');
    // Route::post('/sendotp', 'Home\SubdomainCheckController@sendOtp')->name('send.otp');
    Route::post('/verifyotp', 'Home\SubdomainCheckController@verifyOtp')->name('verify.otp');
    Route::get('/sendotp', 'MainDomain\HomeController@sendOtp')->name('send.otp');
    Route::post('/sendotp', 'MainDomain\HomeController@verifyOtp')->name('send.otp');
    Route::post('/verify', 'Home\VerifyController@verifyMobile')->name('verify');

    Route::get('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@index']);
    Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::get('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@index1']);
    Route::post('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@storeinfo1']);

    Route::get('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@index2']);
    Route::post('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@storeinfo2']);

    Route::get('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@index3']);
    Route::post('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@storeinfo3']);

    Route::get('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@companylogo']);
    Route::post('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@storecompanylogo']);

    Route::get('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@profilelogo']);
    Route::post('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@storeprofilelogo']);

    Route::get('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@passwordreset']);
    Route::post('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@storepassword']);

// Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::resource('skills', 'MainDomain\SkillController');
    Route::resource('achievements', 'MainDomain\AchievementController');
    Route::resource('product', 'MainDomain\ProductController');
    Route::resource('payment', 'MainDomain\PaymentController');
    Route::resource('social', 'MainDomain\SocialController');
    Route::resource('experience', 'MainDomain\ExperienceController');
    Route::resource('education', 'MainDomain\EducationController');
    Route::resource('testimonial', 'MainDomain\TestimonialController');
    Route::resource('subscription', 'MainDomain\SubscriptionController');
    Route::resource('referral', 'MainDomain\ReferralController');
    Route::resource('plan', 'MainDomain\PlanController');
    Route::resource('colorschema', 'MainDomain\ColorController');
    Route::resource('images', 'MainDomain\ImageGalleryController');
    Route::resource('location', 'MainDomain\LocationController');

    Route::get('plansub', ['as' => 'plansub', 'uses' => 'MainDomain\PlanController@CustomSubscribe']);

    Route::resource('preview', 'MainDomain\PreviewController');

    Route::get('clear_cache', function () {
        \Artisan::call('optimize:clear');
        return "Optimize is cleared";
    });

    Route::get('paypayment', ['as' => 'pay_payment', 'uses' => 'MainDomain\PayumoneyController@payment']);

    Route::get('paypayment/status', ['as' => 'pay_payment.status', 'uses' => 'MainDomain\PayumoneyController@status']);

    // Get Route For Show Payment Form
    Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay');
    Route::post('paysuccess', 'RazorpayController@paysuccess');
    Route::post('makesubscription', ['as' => 'makesubscription', 'uses' => 'RazorpayController@makeSubscription']);
    Route::post('razor-thank-you', 'RazorpayController@thankYou');

    // route for to show payment form using get method
    Route::get('pay', 'RazorpayController@pay')->name('pay');

    Route::get('getpaln/{planid}', 'RazorpayController@getPlanbyid')->name('getplan');

    // route for make payment request using post method
    Route::post('dopayment', 'RazorpayController@dopayment')->name('dopayment');
    Route::post('razorpayment', 'RazorpayController@razorPaySuccess')->name('razorpayment');

});

Route::group(['domain' => '{account}.' . \Config::get('app.base_url')], function () {

    /*
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/account', function ($account) {
    return $account;
    });
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Subdomain\DashboardController@index']);
     */
    Route::get('/', ['as' => 'vcard', 'uses' => 'Subdomain\DashboardController@index', 'middleware' => 'sub_domain_shift']);
    Route::get('/savecard', ['as' => 'makecard', 'uses' => 'Subdomain\DashboardController@CreateVcard', 'middleware' => 'sub_domain_shift']);
    Route::get('/qrcode', ['as' => 'qrcode', 'uses' => 'Subdomain\DashboardController@CreateQrcode', 'middleware' => 'sub_domain_shift']);
});

// Route::get('crop-image', 'ImageCropController@index');
// Route::post('crop-image', ['as' => 'croppie.upload-image', 'uses' => 'ImageCropController@imageCrop']);

// Route::get('image_crop', 'ImageCropController@index1');
// Route::post('image_crop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('imagecrop', 'ImageCropController@index2');
// Route::post('imagecrop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@createStep1']);
// Route::post('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@postCreateStep1']);

// Route::get('step2', 'PersonalInfoController@createStep2');
// Route::post('step2', 'PersonalInfoController@postCreateStep2');
// Route::post('remove-image', 'PersonalInfoController@removeImage');

// Route::get('step3', 'PersonalInfoController@createStep3');
// Route::post('store', 'PersonalInfoController@store');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Social.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    protected $connection = 'subdb';

    protected $table = 'tbl_social';

    protected $fillable = [
        'sname', 'svalue',
    ];
}

app/Http/Controllers/MainDomain/SocialController.php
<?php

namespace App\Http\Controllers\MainDomain;

use App\Http\Controllers\Controller;
use App\Social;
use App\Traits\GetSubDomain;
use Illuminate\Http\Request;

class SocialController extends Controller
{
    use GetSubDomain;

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    public function index()
    {
        $this->getdb();

        $socials = Social::latest()->paginate(5);

        return view('social.index', compact('socials'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('social.create');
    }

    public function store(Request $request)
    {
        $this->getdb();

        $request->validate([
            'sname' => 'required',
            'svalue' => 'required',
        ]);

        Social::create($request->all());

        return redirect()->route('social.index')
            ->with('success', 'Social created successfully.');
    }

    public function show($id)
    {
        $this->getdb();
        $social = Social::find($id);
        return view('social.show', compact('social'));
    }

    public function edit($id)
    {
        $this->getdb();
        $social = Social::find($id);
        return view('social.edit', compact('social'));
    }

    public function update(Request $request, $id)
    {
        $this->getdb();
        $social = Social::find($id);

        $request->validate([
            'sname' => 'required',
            'svalue' => 'required',
        ]);

        $social->update($request->all());

        return redirect()->route('social.index')
            ->with('success', 'Social updated successfully');
    }

    public function destroy($id)
    {
        $this->getdb();
        $social = Social::findOrFail($id);
        $social->delete();

        return redirect()->route('social.index')
            ->with('success', 'Social deleted successfully');
    }
}

resources/views/social/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add Social Link</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('social.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('social.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{-- <input type="text" name="sname" class="form-control" placeholder="Name"> --}}
                <select class="form-control" name="sname">
                    <option value="" selected="selected">Choose Social Link</option>
                    <option value="fa-facebook-f">Facebook</option>
                    <option value="fa-twitter">Twitter</option>
                    <option value="fa-google">Google</option>
                    <option value="fa-linkedin-in">LinkedIn</option>
                    <option value="fa-youtube">YouTube</option>
                    <option value="fa-instagram">Instagram</option>
                    <option value="fa-quora ">Quora</option>
                    <option value="fa-google-play">Google Play Store</option>
                    <option value="fa-app-store-ios">App Store IOS</option>
                    <option value="fa-bullhorn">Podcast</option>
                    <option value="fa-blogger">Blogger</option>
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Detail:</strong>
                <input type="url" name="svalue" class="form-control" placeholder="e.g. https://paypal.me/yourname">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/social/edit.blade.php
@extends('layouts.app')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Social Link</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('social.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('social.update',$social->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="sname" value="{{ $social->sname }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <input type="url" class="form-control" name="svalue" placeholder="e.g. https://paypal.me/yourname" value="{{ $social->svalue }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/social/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Social Link List</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('social.create') }}">Add</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Social Name</th>
            <th>Social Link</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($socials as $social)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $social->sname }}</td>
            <td>{{ $social->svalue }}</td>
            <td>
                <form action="{{ route('social.destroy',$social->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('social.show',$social->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('social.edit',$social->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $socials->links() !!}
      
@endsection

resources/views/social/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Payment Link</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('payment.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $payment->sname }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $payment->svalue }}
            </div>
        </div>
    </div>
@endsection