routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Auth::routes();

Route::group(['domain' => \Config::get('app.base_url')], function () {

    Auth::routes();

    Route::get('/', function () {
        return view('landing');
    });
    Route::get('/health', function () {
        response()->json(['success' => 'success'], 200);
    });
    Route::get('/users', function () {
        // $users = \DB::connection('maindb')->table('users')->get();
        $users = \App\User::find(14);
        return $users;
    });

    Route::get('home', 'MainDomain\HomeController@index')->name('home.maindomain');
    Route::post('dashboard', ['as' => 'dashboard', 'uses' => 'MainDomain\HomeController@dashboard']);

    Route::post('/subdomain/check', 'Home\SubdomainCheckController@check')->name('subdomain.check');
    Route::post('/mobile/check', 'Home\SubdomainCheckController@check')->name('mobile.check');
    // Route::post('/sendotp', 'Home\SubdomainCheckController@sendOtp')->name('send.otp');
    Route::post('/verifyotp', 'Home\SubdomainCheckController@verifyOtp')->name('verify.otp');
    Route::get('/sendotp', 'MainDomain\HomeController@sendOtp')->name('send.otp');
    Route::post('/sendotp', 'MainDomain\HomeController@verifyOtp')->name('send.otp');
    Route::post('/verify', 'Home\VerifyController@verifyMobile')->name('verify');

    Route::get('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@index']);
    Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::get('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@index1']);
    Route::post('userinfo1', ['as' => 'userinfo1', 'uses' => 'MainDomain\UserinfoController@storeinfo1']);

    Route::get('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@index2']);
    Route::post('userinfo2', ['as' => 'userinfo2', 'uses' => 'MainDomain\UserinfoController@storeinfo2']);

    Route::get('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@index3']);
    Route::post('userinfo3', ['as' => 'userinfo3', 'uses' => 'MainDomain\UserinfoController@storeinfo3']);

    Route::get('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@companylogo']);
    Route::post('companylogo', ['as' => 'companylogo', 'uses' => 'MainDomain\UserinfoController@storecompanylogo']);

    Route::get('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@profilelogo']);
    Route::post('profilelogo', ['as' => 'profilelogo', 'uses' => 'MainDomain\UserinfoController@storeprofilelogo']);

    Route::get('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@passwordreset']);
    Route::post('password/change', ['as' => 'password.change', 'uses' => 'MainDomain\UserinfoController@storepassword']);

// Route::post('userinfo', ['as' => 'userinfo', 'uses' => 'MainDomain\UserinfoController@storePersonalinfo']);

    Route::resource('skills', 'MainDomain\SkillController');
    Route::resource('achievements', 'MainDomain\AchievementController');
    Route::resource('product', 'MainDomain\ProductController');
    Route::resource('payment', 'MainDomain\PaymentController');
    Route::resource('social', 'MainDomain\SocialController');
    Route::resource('experience', 'MainDomain\ExperienceController');
    Route::resource('education', 'MainDomain\EducationController');
    Route::resource('testimonial', 'MainDomain\TestimonialController');
    Route::resource('subscription', 'MainDomain\SubscriptionController');
    Route::resource('referral', 'MainDomain\ReferralController');
    Route::resource('plan', 'MainDomain\PlanController');
    Route::resource('colorschema', 'MainDomain\ColorController');
    Route::resource('images', 'MainDomain\ImageGalleryController');
    Route::resource('location', 'MainDomain\LocationController');

    Route::get('plansub', ['as' => 'plansub', 'uses' => 'MainDomain\PlanController@CustomSubscribe']);

    Route::resource('preview', 'MainDomain\PreviewController');

    Route::get('clear_cache', function () {
        \Artisan::call('optimize:clear');
        return "Optimize is cleared";
    });

    Route::get('paypayment', ['as' => 'pay_payment', 'uses' => 'MainDomain\PayumoneyController@payment']);

    Route::get('paypayment/status', ['as' => 'pay_payment.status', 'uses' => 'MainDomain\PayumoneyController@status']);

    // Get Route For Show Payment Form
    Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay');
    Route::post('paysuccess', 'RazorpayController@paysuccess');
    Route::post('makesubscription', ['as' => 'makesubscription', 'uses' => 'RazorpayController@makeSubscription']);
    Route::post('razor-thank-you', 'RazorpayController@thankYou');

    // route for to show payment form using get method
    Route::get('pay', 'RazorpayController@pay')->name('pay');

    Route::get('getpaln/{planid}', 'RazorpayController@getPlanbyid')->name('getplan');

    // route for make payment request using post method
    Route::post('dopayment', 'RazorpayController@dopayment')->name('dopayment');
    Route::post('razorpayment', 'RazorpayController@razorPaySuccess')->name('razorpayment');

});

Route::group(['domain' => '{account}.' . \Config::get('app.base_url')], function () {

    /*
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/account', function ($account) {
    return $account;
    });
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'Subdomain\DashboardController@index']);
     */
    Route::get('/', ['as' => 'vcard', 'uses' => 'Subdomain\DashboardController@index', 'middleware' => 'sub_domain_shift']);
    Route::get('/savecard', ['as' => 'makecard', 'uses' => 'Subdomain\DashboardController@CreateVcard', 'middleware' => 'sub_domain_shift']);
    Route::get('/qrcode', ['as' => 'qrcode', 'uses' => 'Subdomain\DashboardController@CreateQrcode', 'middleware' => 'sub_domain_shift']);
});

// Route::get('crop-image', 'ImageCropController@index');
// Route::post('crop-image', ['as' => 'croppie.upload-image', 'uses' => 'ImageCropController@imageCrop']);

// Route::get('image_crop', 'ImageCropController@index1');
// Route::post('image_crop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('imagecrop', 'ImageCropController@index2');
// Route::post('imagecrop/upload', 'ImageCropController@upload')->name('image_crop.upload');

// Route::get('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@createStep1']);
// Route::post('step1', ['as' => 'personal_info.step1', 'uses' => 'PersonalInfoController@postCreateStep1']);

// Route::get('step2', 'PersonalInfoController@createStep2');
// Route::post('step2', 'PersonalInfoController@postCreateStep2');
// Route::post('remove-image', 'PersonalInfoController@removeImage');

// Route::get('step3', 'PersonalInfoController@createStep3');
// Route::post('store', 'PersonalInfoController@store');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/MainDomain/PlanController.php
<?php

namespace App\Http\Controllers\MainDomain;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Rinvex\Subscriptions\Models\Plan;
use Rinvex\Subscriptions\Models\PlanFeature;
use Rinvex\Subscriptions\Models\PlanSubscription;
use Rinvex\Subscriptions\Models\PlanSubscriptionUsage;

class PlanController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth']);
    }

    public function index()
    {
        $user = \Auth::user();
        $plans = Plan::all();
        // dd($plans);
        $psub = new PlanSubscription();
        $data = $psub->where('user_id', $user->id)->first();
        $data['is_active'] = $user->subscription($data->slug)->active();
        $data['is_ended'] = $user->subscription($data->slug)->ended();
        return view('plan.index', compact('plans', 'data'));

    }

    public function CustomSubscribe()
    {
        $plan = new Plan();
        $paln1 = new PlanFeature();
        $paln2 = new PlanSubscription();
        $paln3 = new PlanSubscriptionUsage();

        /*$plan = app('rinvex.subscriptions.plan')->create([
        'name' => 'Free',
        'description' => 'Free plan',
        'price' => 0.00,
        'signup_fee' => 0.00,
        'invoice_period' => 0,
        'invoice_interval' => 'month',
        'trial_period' => 0,
        'trial_interval' => 'day',
        'sort_order' => 1,
        'currency' => 'INR',
        ]);

        $plan = app('rinvex.subscriptions.plan')->create([
        'name' => 'Premium',
        'description' => 'Premium plan',
        'price' => 500.00,
        'signup_fee' => 200.00,
        'invoice_period' => 12,
        'invoice_interval' => 'month',
        'trial_period' => 0,
        'trial_interval' => 'day',
        'sort_order' => 2,
        'currency' => 'INR',
        ]);

        $plan = app('rinvex.subscriptions.plan')->create([
        'name' => 'Gold',
        'description' => 'Gold plan',
        'price' => 1000.00,
        'signup_fee' => 400.00,
        'invoice_period' => 12,
        'invoice_interval' => 'month',
        'trial_period' => 0,
        'trial_interval' => 'day',
        'sort_order' => 3,
        'currency' => 'INR',
        ]);
         */
        // Create multiple plan features at once
        // $plan->features()->saveMany([
        //     new PlanFeature(['name' => 'listings', 'value' => 50, 'sort_order' => 1]),
        //     new PlanFeature(['name' => 'pictures_per_listing', 'value' => 10, 'sort_order' => 5]),
        //     new PlanFeature(['name' => 'listing_duration_days', 'value' => 30, 'sort_order' => 10, 'resettable_period' => 1, 'resettable_interval' => 'month']),
        //     new PlanFeature(['name' => 'listing_title_bold', 'value' => 'Y', 'sort_order' => 15]),
        // ]);

        // $plan = $plan->find(3);
        // dd($plan); // get plan info
        // Check if the plan is free
        // dd($plan->isFree());

        // Check if the plan has trial period
        // dd($plan->hasTrial());

        // Check if the plan has grace period
        // dd($plan->hasGrace());

        //user subscribe the plan
        // $user = \App\User::find(17);
        // $plan = app('rinvex.subscriptions.plan')->find(1);

        // $user->newSubscription('free', $plan);

        // Get bookings of the given user
        // $user = \App\User::find(17);
        // $bookingsOfUser = app('rinvex.subscriptions.plan_subscription')->ofUser($user)->get();

        // Get subscriptions by plan
        // $subscriptions = app('rinvex.subscriptions.plan_subscription')->byPlanId(3)->get();
        // $subscriptions = app('rinvex.subscriptions.plan_subscription')->findEndingTrial(3)->get();

        // dd($subscriptions);

        $plan = app('rinvex.subscriptions.plan')->find(2);
        $subscription = app('rinvex.subscriptions.plan_subscription')->where('user_id', 17)->first();

        //dd($subscription);
        // Change subscription plan
        $subscription->changePlan($plan);
    }
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/plan/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('product.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('product.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="sname" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Detail:</strong>
                <textarea class="form-control" style="height:150px" name="svalue" placeholder="Short Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/plan/edit.blade.php
@extends('layouts.app')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('product.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('product.update',$product->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="sname" value="{{ $product->sname }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="svalue" placeholder="Detail">{{ $product->svalue }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/plan/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Plan List</h2>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   {{$data}}
    <div class="container">
        @foreach ($plans as $plan)
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>{{$plan->name.'<==>'.$plan->slug}}</h2>
                    </div>
                    @if ($plan->id == $data->plan_id && $data->is_active == true)
                        <div class="pull-right">
                        <form action="{{route('subscription.store')}}" method="post">
                            @csrf
                                <input type="hidden" name="id" value="{{$plan->id}}">
                                <input type="hidden" name="sub_id" value="{{$data->id}}">
                                <input type="hidden" name="sub_name" value="unsubscribe">
                                <input type="hidden" name="slug" value="{{$data->slug}}">
                                <button type="submit" class="btn btn-success">UnSubscribe</button>
                                <button type="button" class="btn btn-success" onclick="changePlan('unsubscribe');">UnSubscribe</button>
                            </form>
                        </div>
                    @elseif ($plan->id == $data->plan_id && $data->is_ended == true)
                            <div class="pull-right">
                                <form action="{{route('subscription.store')}}" method="post">
                                    @csrf
                                    <input type="hidden" name="id" value="{{$plan->id}}">
                                    <input type="hidden" name="sub_name" value="renew">
                                    <input type="hidden" name="amount" value="{{$plan->price}}">
                                    <input type="hidden" name="slug" value="{{$data->slug}}">
                                    <button type="submit" class="btn btn-success">Renew</button>
                                    <button type="submit" class="btn btn-success" onclick="payment(this);" data-amount="{{$plan->price}}" data-planid="{{$plan->id}}" data-planslug="{{$plan->slug}}">Renew</button>
                                </form>
                            </div>
                        @else
                        <div class="pull-right">
                            <form action="{{route('pay_payment')}}" method="get">
                            <input type="hidden" name="id" value="{{$plan->id}}">
                                <input type="hidden" name="amount" value="{{$plan->price}}">
                                <input type="hidden" name="slug" value="{{$plan->slug}}">
                                <input type="hidden" name="">
                                <button type="submit" class="btn btn-success">SubScribe To Plan</button>
                                <button type="button" class="btn btn-success" onclick="payment(this);" data-amount="{{$plan->price}}" data-planid="{{$plan->id}}" data-planslug="{{$plan->slug}}">SubScribe To Plan Razor</button>
                            </form>
                        </div>
                    @endif
                  
                </div>
            </div>
        @endforeach
    </div>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>

    function payment(plan){

        // var amount = getPlansDetails('plan_FNRbRXj2UqXeFA');
        // return
        var totalAmount = $(plan).attr("data-amount");
        var planid = $(plan).attr("data-planid");
        var planslug = $(plan).attr("data-planslug");
        var options = {
        key: "{{ Config::get('razor.razor_key') }}",
        amount: totalAmount * 100,
        handler: function (response){
            demoSuccessHandler(response,planid,planslug);
        },
        "prefill": {
               "contact": "{{\Auth::user()->mobile}}",
               "email":   "{{\Auth::user()->email}}",
           },
    }

    window.r = new Razorpay(options);
    r.open();
    
    }

    function demoSuccessHandler(transaction,planid,planslug) {
        // console.log(transaction);
        $.ajax({
            method: 'post',
            url: "{!!route('razorpayment')!!}",
            data: {
                "_token": "{{ csrf_token() }}",
                "payment_id": transaction.razorpay_payment_id,
                "plan_id":planid
            },
            success: function (msg) {
                data = JSON.parse(JSON.stringify(msg));
                if(data.status){
                    location.reload()
                }else{
                    alert('Something Went Wrong');
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
            console.log(textStatus, errorThrown);
            },
            complete: function (r) {
                console.log('complete');
                console.log(r);
            }
        })
    }

    function changePlan(subname){
        $.ajax({
            method: 'post',
            url: "{!!route('subscription.store')!!}",
            data: {
                "_token": "{{ csrf_token() }}",
                "sub_name": subname,
            },
            success: function (msg) {
                data = JSON.parse(JSON.stringify(msg));
                if(data.status){
                    location.reload()
                }else{
                    alert('Something Went Wrong');
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
            console.log(textStatus, errorThrown);
            }
        })
    }
</script>
      
@endsection

resources/views/plan/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('product.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->sname }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $product->svalue }}
            </div>
        </div>
    </div>
@endsection